export interface NavSection {
  title: string;
  items: Array<{ title: string; href: string }>;
}

export const navigation: NavSection[] = [
  {
    title: "Getting Started",
    items: [
      { title: "Introduction", href: "/docs" },
      { title: "Installation", href: "/docs/installation" },
      { title: "CLI", href: "/docs/cli" },
      { title: "Theming", href: "/docs/theming" },
      { title: "Dark Mode", href: "/docs/dark-mode" },
    ],
  },
  {
    title: "Components",
    items: [
      { title: "All components", href: "/docs/components" },
      { title: "Accordion", href: "/docs/components/accordion" },
      { title: "Alert", href: "/docs/components/alert" },
      { title: "Alert Dialog", href: "/docs/components/alert-dialog" },
      { title: "Avatar", href: "/docs/components/avatar" },
      { title: "Badge", href: "/docs/components/badge" },
      { title: "Breadcrumb", href: "/docs/components/breadcrumb" },
      { title: "Button", href: "/docs/components/button" },
      { title: "Card", href: "/docs/components/card" },
      { title: "Checkbox", href: "/docs/components/checkbox" },
      { title: "Combobox", href: "/docs/components/combobox" },
      { title: "Command", href: "/docs/components/command" },
      { title: "Date Picker", href: "/docs/components/date-picker" },
      { title: "Dialog", href: "/docs/components/dialog" },
      { title: "Dropdown Menu", href: "/docs/components/dropdown-menu" },
      { title: "Empty State", href: "/docs/components/empty-state" },
      { title: "Footer", href: "/docs/components/footer" },
      { title: "Form", href: "/docs/components/form" },
      { title: "Hover Card", href: "/docs/components/hover-card" },
      { title: "Input", href: "/docs/components/input" },
      { title: "Input OTP", href: "/docs/components/input-otp" },
      { title: "Kbd", href: "/docs/components/kbd" },
      { title: "Layout", href: "/docs/components/layout" },
      { title: "Navbar", href: "/docs/components/navbar" },
      { title: "Pagination", href: "/docs/components/pagination" },
      { title: "Popover", href: "/docs/components/popover" },
      { title: "Progress", href: "/docs/components/progress" },
      { title: "Radio Group", href: "/docs/components/radio-group" },
      { title: "Rating", href: "/docs/components/rating" },
      { title: "Select", href: "/docs/components/select" },
      { title: "Separator", href: "/docs/components/separator" },
      { title: "Sheet", href: "/docs/components/sheet" },
      { title: "Sidebar", href: "/docs/components/sidebar" },
      { title: "Skeleton", href: "/docs/components/skeleton" },
      { title: "Slider", href: "/docs/components/slider" },
      { title: "Spinner", href: "/docs/components/spinner" },
      { title: "Stat", href: "/docs/components/stat" },
      { title: "Stepper", href: "/docs/components/stepper" },
      { title: "Switch", href: "/docs/components/switch" },
      { title: "Table", href: "/docs/components/table" },
      { title: "Tabs", href: "/docs/components/tabs" },
      { title: "Textarea", href: "/docs/components/textarea" },
      { title: "Theme Provider", href: "/docs/components/theme-provider" },
      { title: "Timeline", href: "/docs/components/timeline" },
      { title: "Toast", href: "/docs/components/toast" },
      { title: "Toggle", href: "/docs/components/toggle" },
      { title: "Tooltip", href: "/docs/components/tooltip" },
    ],
  },
  {
    title: "3D",
    items: [
      { title: "Tilt", href: "/docs/components/tilt" },
      { title: "Holo Card", href: "/docs/components/holo-card" },
      { title: "Flip Card", href: "/docs/components/flip-card" },
      { title: "Cube", href: "/docs/components/cube" },
      { title: "Card Stack", href: "/docs/components/card-stack" },
      { title: "Coverflow", href: "/docs/components/coverflow" },
      { title: "Carousel 3D", href: "/docs/components/carousel-3d" },
      { title: "Parallax", href: "/docs/components/parallax" },
      { title: "Pin 3D", href: "/docs/components/pin-3d" },
      { title: "Marquee 3D", href: "/docs/components/marquee-3d" },
      { title: "Spotlight", href: "/docs/components/spotlight" },
      { title: "Lens", href: "/docs/components/lens" },
      {
        title: "Direction-aware Hover",
        href: "/docs/components/direction-aware-hover",
      },
      { title: "Meteors", href: "/docs/components/meteors" },
      { title: "Aurora", href: "/docs/components/aurora" },
      { title: "Moving Border", href: "/docs/components/moving-border" },
      { title: "Orbiting Circles", href: "/docs/components/orbiting-circles" },
      { title: "Sparkles", href: "/docs/components/sparkles" },
      {
        title: "Infinite Moving Cards",
        href: "/docs/components/infinite-moving-cards",
      },
      {
        title: "Hover Border Gradient",
        href: "/docs/components/hover-border-gradient",
      },
      { title: "Lamp", href: "/docs/components/lamp" },
      { title: "Magnet", href: "/docs/components/magnet" },
      { title: "Animated Text", href: "/docs/components/animated-text" },
      { title: "Number Ticker", href: "/docs/components/number-ticker" },
      { title: "Neon Glow", href: "/docs/components/neon-glow" },
      {
        title: "Background Beams",
        href: "/docs/components/background-beams",
      },
      {
        title: "Background Boxes",
        href: "/docs/components/background-boxes",
      },
      { title: "Wavy Background", href: "/docs/components/wavy-background" },
      {
        title: "Following Pointer",
        href: "/docs/components/following-pointer",
      },
      { title: "Compare", href: "/docs/components/compare" },
      {
        title: "Card Hover Effect",
        href: "/docs/components/card-hover-effect",
      },
      { title: "Sparkles Text", href: "/docs/components/sparkles-text" },
      {
        title: "Multi Step Loader",
        href: "/docs/components/multi-step-loader",
      },
      { title: "World Map", href: "/docs/components/world-map" },
      { title: "Globe", href: "/docs/components/globe" },
      { title: "Tracing Beam", href: "/docs/components/tracing-beam" },
      {
        title: "Animated Tooltip",
        href: "/docs/components/animated-tooltip",
      },
      { title: "Bento Grid", href: "/docs/components/bento-grid" },
      { title: "Floating Dock", href: "/docs/components/floating-dock" },
      { title: "Wavy Text", href: "/docs/components/wavy-text" },
      { title: "Evervault Card", href: "/docs/components/evervault-card" },
      { title: "Flux Panels", href: "/docs/components/flux-panels" },
      { title: "File Upload", href: "/docs/components/file-upload" },
      { title: "Focus Cards", href: "/docs/components/focus-cards" },
      { title: "Gravity Well", href: "/docs/components/gravity-well" },
      { title: "Holo Slices", href: "/docs/components/holo-slices" },
      { title: "Neon Portal", href: "/docs/components/neon-portal" },
      { title: "Orbit Stack", href: "/docs/components/orbit-stack" },
      { title: "Plasma Field", href: "/docs/components/plasma-field" },
      { title: "Prism Orb", href: "/docs/components/prism-orb" },
      { title: "Quantum Grid", href: "/docs/components/quantum-grid" },
      { title: "Dot Pattern", href: "/docs/components/dot-pattern" },
      {
        title: "Text Generate Effect",
        href: "/docs/components/text-generate-effect",
      },
      { title: "Flip Words", href: "/docs/components/flip-words" },
      { title: "Ripple", href: "/docs/components/ripple" },
      { title: "Text Scramble", href: "/docs/components/text-scramble" },
      { title: "Tilt Tiles", href: "/docs/components/tilt-tiles" },
      { title: "Helix", href: "/docs/components/helix" },
      { title: "Page Curl", href: "/docs/components/page-curl" },
      { title: "Swipe Stack", href: "/docs/components/swipe-stack" },
      { title: "Magnetic Button", href: "/docs/components/magnetic-button" },
      { title: "Cursor Trail", href: "/docs/components/cursor-trail" },
      { title: "Orbital Menu", href: "/docs/components/orbital-menu" },
      { title: "Wave Grid", href: "/docs/components/wave-grid" },
      { title: "Magic Layer", href: "/docs/components/magic-layer" },
      { title: "Paper Plane", href: "/docs/components/paper-plane" },
      { title: "Coin Flip", href: "/docs/components/coin-flip" },
      { title: "Fold Out", href: "/docs/components/fold-out" },
      { title: "Pin Board", href: "/docs/components/pin-board" },
      { title: "Glitch Clip", href: "/docs/components/glitch-clip" },
      { title: "Phone Mockup", href: "/docs/components/phone-mockup" },
      { title: "Pricing Cards", href: "/docs/components/pricing-cards" },
      { title: "Logo Cloud", href: "/docs/components/logo-cloud" },
      { title: "Testimonial Quote", href: "/docs/components/testimonial-quote" },
      { title: "Stat Card", href: "/docs/components/stat-card" },
      { title: "Animated Chart", href: "/docs/components/animated-chart" },
      { title: "Feature Card", href: "/docs/components/feature-card" },
      { title: "Notification Stack", href: "/docs/components/notification-stack" },
      { title: "Copy Button", href: "/docs/components/copy-button" },
      { title: "Count Up Ring", href: "/docs/components/count-up-ring" },
      { title: "Dot Progress", href: "/docs/components/dot-progress" },
      { title: "Theme Toggle", href: "/docs/components/theme-toggle" },
      { title: "Number Flip", href: "/docs/components/number-flip" },
      { title: "Hold to Confirm", href: "/docs/components/hold-to-confirm" },
      { title: "Vote Widget", href: "/docs/components/vote-widget" },
      { title: "Segmented Control", href: "/docs/components/segmented-control" },
      { title: "Avatar Stack", href: "/docs/components/avatar-stack" },
      { title: "Activity Heatmap", href: "/docs/components/activity-heatmap" },
      { title: "Gauge Meter", href: "/docs/components/gauge-meter" },
      { title: "Chat Bubble", href: "/docs/components/chat-bubble" },
      { title: "Comparison Table", href: "/docs/components/comparison-table" },
      { title: "Tag Input", href: "/docs/components/tag-input" },
      { title: "Number Input", href: "/docs/components/number-input" },
      { title: "Scroll Progress", href: "/docs/components/scroll-progress" },
      { title: "Banner", href: "/docs/components/banner" },
      { title: "Kanban Board", href: "/docs/components/kanban-board" },
      { title: "Tree View", href: "/docs/components/tree-view" },
      { title: "Color Picker", href: "/docs/components/color-picker" },
      { title: "Resizable", href: "/docs/components/resizable" },
      { title: "Data Table", href: "/docs/components/data-table" },
      { title: "Context Menu", href: "/docs/components/context-menu" },
      { title: "Time Picker", href: "/docs/components/time-picker" },
      { title: "Toolbar", href: "/docs/components/toolbar" },
      { title: "Confetti", href: "/docs/components/confetti" },
      { title: "Animated Beam", href: "/docs/components/animated-beam" },
      { title: "Scratch Card", href: "/docs/components/scratch-card" },
      { title: "Retro Grid", href: "/docs/components/retro-grid" },
    ],
  },
];
